controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: forward_command_controller/ForwardCommandController

position_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - FL_hip_yaw
      - FL_hip_pitch
      - FL_knee
      - FR_hip_yaw
      - FR_hip_pitch
      - FR_knee
      - RR_hip_yaw
      - RR_hip_pitch
      - RR_knee
      - RL_hip_yaw
      - RL_hip_pitch
      - RL_knee
    interface_name: position